retrie check script

diff --git a/.github/workflows/lint-and-test.yml b/.github/workflows/lint-and-test.yml
--- a/.github/workflows/lint-and-test.yml
+++ b/.github/workflows/lint-and-test.yml
@@ -101,16 +101,16 @@ jobs:
           args: docker restart solrservice
       - name: Ensure Solr is running
         run: |
-          retries=5
-          while (( $retries > 0 )); do
-            curl -I -fs http://solr:8983/solr/ && break
-            echo "no response from Solr, ${retries} / 5 remaining"
-            (( $retries --))
-            sleep 5
+          retries=5; \
+          while [[ $retries > 0 ]]; do
+            curl -I -fs http://solr:8983/solr/ && break;
+            echo "no response from Solr, ${retries} / 5 remaining";
+            retries=$(( $retries - 1 ));
+            sleep 5;
           done
-          if (( $retries == 0 )); then
-            echo "out of retries! couldn't connect to Solr"
-            exit 1
+          if [[ $retries -eq 0 ]]; then
+            echo "out of retries! couldn't connect to Solr";
+            exit 1;
           fi
       -
         name: Setup Firefox
